name: "UCTronics RM0013 Display"
description: "Configurable full-color display for the UCTronics RM0013 with corrected bitmap logo rendering"
url: "https://github.com/iamvinyl/UCTRONICS_RM0004_HA/tree/main/uc_tronics_display"
version: "1.2.3"
slug: "uc_tronics_display"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
gpio: true
full_access: true
devices:
  - "/dev/i2c-1"
privileged:
  - "SYS_ADMIN"
hassio_api: true
options:
  show_home_assistant_logo: true
  show_ip_address: true
  show_cpu_usage: true
  show_ram_usage: true
  show_disk_space: true
  screen_duration: 5
schema:
  show_home_assistant_logo: bool
  show_ip_address: bool
  show_cpu_usage: bool
  show_ram_usage: bool
  show_disk_space: bool
  screen_duration: "int(2,60)"
